services:
  - type: web
    name: cares-work-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: GOOGLE_CREDS_JSON
        sync: false
      - key: TOKEN
        sync: false
